---

- name: install python passlib
  apt:
    name: "{{item}}"
    state: latest
    dpkg_options: 'force-confnew,force-confdef'
    autoremove: yes
    update_cache: yes
  with_items:
  - python-passlib

...
